"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function AutomationForm(){
  const router = useRouter();
  const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const payload={name:f.get("name"),triggerType:"inbound_email",priority:Number(f.get("priority")||100),conditions:{fromContains:f.get("fromContains")||undefined,subjectContains:f.get("subjectContains")||undefined,bodyContains:f.get("bodyContains")||undefined,knownContact:f.get("knownContact")==="on"},actions:[f.get("action")==="ai_reply"?{type:"ai_reply",mode:f.get("replyMode"),delayMinutes:Number(f.get("delayMinutes")||5),instructions:f.get("instructions")||undefined}:{type:f.get("action")} ]};if(process.env.NEXT_PUBLIC_DEMO_MODE!=="false"){setStatus("Demo: automation rule validated.");return;}setBusy(true);try{const r=await fetch("/api/automations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save rule");router.push("/automations")}catch(e){setStatus(e instanceof Error?e.message:"Could not save rule")}finally{setBusy(false)}}
  const cls="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm";
  return <form onSubmit={submit} className="card max-w-4xl p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Rule name<input name="name" required className={cls} placeholder="AI draft for known clients"/></label><label className="text-sm font-semibold">From contains<input name="fromContains" className={cls} placeholder="@client.com"/></label><label className="text-sm font-semibold">Subject contains<input name="subjectContains" className={cls} placeholder="proposal"/></label><label className="text-sm font-semibold sm:col-span-2">Body contains<input name="bodyContains" className={cls} placeholder="Optional keyword"/></label><label className="flex items-center gap-2 text-sm font-semibold"><input name="knownContact" type="checkbox"/> Known contacts only</label><label className="text-sm font-semibold">Priority<input name="priority" type="number" defaultValue="100" className={cls}/></label><label className="text-sm font-semibold">Action<select name="action" className={cls}><option value="ai_reply">AI reply</option><option value="mark_read">Mark read</option><option value="archive">Archive</option></select></label><label className="text-sm font-semibold">AI mode<select name="replyMode" className={cls}><option value="draft">Create draft</option><option value="auto_send">Auto-send after delay</option></select></label><label className="text-sm font-semibold">Delay minutes<input name="delayMinutes" type="number" min="0" defaultValue="5" className={cls}/></label><label className="text-sm font-semibold sm:col-span-2">AI instructions<textarea name="instructions" rows={4} className={cls} placeholder="Answer briefly. Do not quote prices unless already stated in the thread."/></label></div><button disabled={busy} className="mt-5 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Save automation</button>{status&&<p className="mt-3 text-sm text-slate-500">{status}</p>}</form>
}
